export const skillsData = [
     "HTML",
     "CSS",
     "JavaScript",
     "TypeScript",
     "React",
     "Next.js",
     "Node.js",
     "Git",
     "Tailwind",
     "Prisma",
     "MongoDB",
     "Redux",
     "Express",
     "PostgreSQL",
   ] as const;